name: CI Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        environment: test
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup node js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm ci

            - name: Run eslint
              run: npm run lint:eslint

            - name: Run prettier
              run: npm run format:check

            - name: Run stylelint
              run: npm run lint:stylelint

            - name: Run test coverage
              run: npm run test:coverage
              env:
                  PORT: ${{ secrets.PORT }}
                  BACKEND_PROXY: ${{ secrets.BACKEND_PROXY }}
                  VITE_ENV: ${{ vars.VITE_ENV }}

    production:
        needs: test
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup node js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install dependencies
              run: npm ci

            - name: Build the application
              run: npm run build
              env:
                  PORT: ${{ secrets.PORT }}
                  BACKEND_PROXY: ${{ secrets.BACKEND_PROXY }}
                  SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
                  VITE_ENV: ${{ vars.VITE_ENV }}

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist
